### ISSUE TITLE
Binaries in "example" directory?

### ISSUE THREAD

**Issue by robert-scheck** [Ed-Yang/eoam#2]
How mature is the software currently? Is it still active and maintained? What's the reason to build the binaries in the "example" directory?

**Comment by Ed-Yang** [comment]
I perform only basic test on this package.  I am still willing to improve this repo, but currently have no device in hand, so any change request will be taken slowly.  I am not a expert on CMake utility, the output binary in "example" or "test" folder, maybe caused by add subproject directive, I guess.  I will look at it at my free time.

**Comment by Ed-Yang** [comment]
Use 
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}) 

to make the binary output to build folder.
